### ISSUE TITLE
"SeqRecord comparison is deliberately not implemented"

### ISSUE THREAD

**Issue by skiaphrene** [bunop/isoSegmenter#1]
Dear bunop,

I would like to use isoSegmenter to generate isochores of the latest assembly of the Human genome (hg38).

As far as I can tell I have successfully installed isoSegmenter & all dependencies on my work Mac (OS 10.10.5), as I can run the code below without issue:
`isoSegmenter.py --help`

However I get the following issue when trying to run it on either a downloaded FASTA file, or even the test FASTA file provided:

```
$ isoSegmenter.py --infile chr21.fa.gz --outfile chr21.isochores.csv --graphfile chr21.isochores.png --draw_legend --verbose
Thu Jul 28 17:47:40 2016: 

isoSegmenter  Copyright (C) 2013-2015 ITB - CNR
This program comes with ABSOLUTELY NO WARRANTY; for details type `isoSegmenter --help'.
This is free software, and you are welcome to redistribute it
under certain conditions; show LICENSE.md for more details.

Thu Jul 28 17:47:40 2016: Opening chr21.fa.gz...
Thu Jul 28 17:47:42 2016: 1 sequences read
Traceback (most recent call last):
  File "/usr/local/bin/isoSegmenter.py", line 164, in <module>
    Chrom = GClib.Elements.Chromosome(seqRecord)
  File "/Library/Python/2.7/site-packages/GClib/Elements.py", line 296, in __init__
    if self.seqRecord != None:
  File "/Library/Python/2.7/site-packages/biopython-1.67-py2.7-macosx-10.10-intel.egg/Bio/SeqRecord.py", line 723, in __ne__
    raise NotImplementedError(_NO_SEQRECORD_COMPARISON)
NotImplementedError: SeqRecord comparison is deliberately not implemented. Explicitly compare the attributes of interest.
```

As far as I can tell this is the correct behaviour from the latest BioPython version:
https://github.com/biopython/biopython/blob/master/Bio/SeqRecord.py
(lines 18, 738-739)
My Python is version 2.7, my BioPython is version 1.67 (c.f. info below)

Do you know if I am missing something, or doing something wrong, or has BioPython changed?

Thanks in advance for your help!

Best regards,

-- Alex

```
$ pip freeze
altgraph==0.10.2
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
bdist-mpkg==0.5.0
biopython==1.67
bonjour-py==0.3
certifi==2016.2.28
Cython==0.23.2
gat==1.2.2
GClib==1.5.0
gdmodule==0.59
h5py==2.6.0
limix==0.7.68
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
nose==1.3.7
numpy==1.8.0rc1
pandas==0.18.0
Pillow==3.3.0
py2app==0.7.3
pyobjc-core==2.5.1
pyobjc-framework-(.........)
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==1.5
pytz==2013.7
scikit-learn==0.17.1
scipy==0.13.0b1
singledispatch==3.4.0.3
six==1.4.1
tornado==4.3
Twisted==13.2.0
xattr==0.6.4
zope.interface==4.1.1

$ python --version
Python 2.7.10
```

**Comment by bunop** [comment]
Thank you, Alex, for this report. It seems that biopython changed its behaviour, I will do some tests and I will update my code to face this issue. I hope to fix it in a sort time.

Regards,

Paolo

**Comment by bunop** [comment]
Dear Alex,

I've updated code and now It seems that `isoSegmenter.py` works even with the lastest biopython version. You need to fetch the updated version and re-install `isoSegmenter`. Thank you for your interest in `isoSegmenter`.

Regards,

Paolo
